"""DeepEval exporter (F-17).

Renders a qval suite into a standalone **pytest file** that follows DeepEval's
``LLMTestCase`` + ``GEval`` pattern. Each qval case becomes a test: the prompt
is the ``input``, the ``expected_behavior`` becomes a GEval ``criteria`` string,
and ``actual_output`` comes from a ``model_under_test()`` stub the user wires to
their own LLM.

Design constraints (enforced by tests):
* The generated source must be syntactically valid standalone Python
  (``compile()``-able), so all string literals are emitted via ``repr()`` and
  docstrings are flattened to one line.
* qval's own environment must not need deepeval installed. The exporter never
  imports deepeval; the *generated* file imports it inside a ``try`` and skips
  cleanly (``pytest.skip``) when it is absent.

GEval reference: https://docs.confident-ai.com/docs/metrics-llm-evals
"""
from __future__ import annotations

import re

from qval.engine.schemas import TestCase
from qval.utils.time_utils import now_utc_iso
from .base import BaseExporter, ExportResult
from .fidelity import FidelityReport, CLEAN, DEGRADED, DROPPED
from .registry import register

DOC_GEVAL = "https://docs.confident-ai.com/docs/metrics-llm-evals"


class DeepEvalExporter(BaseExporter):
    """Exporter for DeepEval (a runnable pytest scaffold)."""

    tool_name = "deepeval"
    default_extension = ".py"

    def export_suite(self, cases: list[TestCase], suite_name: str) -> ExportResult:
        n_tests = sum(2 if c.paired_prompt else 1 for c in cases)
        blocks = [_module_header(suite_name, len(cases), n_tests), _PREAMBLE]
        for case in cases:
            blocks.append(_test_block(case, case.prompt, case.id, paired=False))
            if case.paired_prompt:
                blocks.append(_test_block(case, case.paired_prompt, case.id, paired=True))
        # Two blank lines between top-level blocks (PEP 8 E302) so the emitted
        # file is clean enough to commit as-is.
        text = "\n\n\n".join(blocks).rstrip() + "\n"
        return ExportResult(text=text,
                            fidelity=_fidelity(cases, suite_name, n_tests))


# --- source fragments -------------------------------------------------------

_PREAMBLE = '''import pytest  # noqa: F401

try:
    from deepeval import assert_test
    from deepeval.metrics import GEval
    from deepeval.test_case import LLMTestCase, LLMTestCaseParams
except ImportError:  # deepeval is optional — install it to actually run these.
    pytest.skip("deepeval is not installed", allow_module_level=True)


def model_under_test(prompt: str) -> str:
    """Return your model's response to ``prompt``.

    Wire this to the LLM you are evaluating. It is intentionally left
    unimplemented so this generated file imports cleanly without a live model.
    """
    raise NotImplementedError("Wire model_under_test() to your model under test.")'''


def _module_header(suite_name: str, n_cases: int, n_tests: int) -> str:
    return (
        '"""DeepEval suite — generated by `qval export deepeval` (F-17).\n\n'
        f"suite: {suite_name}   |   {n_cases} qval cases -> {n_tests} deepeval tests\n"
        f"generated: {now_utc_iso()}\n\n"
        "Runnable scaffold:\n"
        "  1. pip install deepeval\n"
        "  2. wire model_under_test() below to the LLM you are evaluating\n"
        "  3. run `deepeval test run <this file>` (or `pytest <this file>`)\n\n"
        "qval risk_level / manual_review_required / detectors have no deepeval\n"
        "equivalent — they are preserved as docstrings only. See the sidecar\n"
        f".fidelity.md for the full translation report.\n\nGEval reference: {DOC_GEVAL}\n"
        '"""'
    )


def _func_name(category: str, qid: str, paired: bool) -> str:
    slug = re.sub(r"[^0-9a-zA-Z]+", "_", f"{category}_{qid}").strip("_").lower()
    return f"test_{slug}{'_paired' if paired else ''}"


def _one_line(text: str) -> str:
    """Flatten arbitrary text for safe placement inside a docstring."""
    return " ".join(text.split()).replace('"""', "'''")


def _test_block(case: TestCase, prompt: str, qid: str, paired: bool) -> str:
    name = _func_name(case.category, qid, paired)
    detectors = ", ".join(case.detectors) or "none"
    doc_lines = [
        f"{qid} · {_one_line(case.name)}{' (paired counterpart)' if paired else ''}",
        f"category: {case.category} | risk_level: {case.risk_level} | "
        f"manual_review_required: {case.manual_review_required}",
        f"scoring_type: {case.scoring_type} | detectors: {detectors}",
        f"expected_behavior: {_one_line(case.expected_behavior)}",
    ]
    docstring = '\n    '.join(doc_lines)
    return (
        f"def {name}():\n"
        f'    """{docstring}\n    """\n'
        f"    prompt = {prompt!r}\n"
        f"    test_case = LLMTestCase(input=prompt, actual_output=model_under_test(prompt))\n"
        f"    criteria = {case.expected_behavior!r}\n"
        f"    metric = GEval(\n"
        f'        name="Expected behavior",\n'
        f"        criteria=criteria,\n"
        f"        evaluation_params=[LLMTestCaseParams.INPUT, LLMTestCaseParams.ACTUAL_OUTPUT],\n"
        f"        threshold=0.5,\n"
        f"    )\n"
        f"    assert_test(test_case, [metric])"
    )


def _fidelity(cases: list[TestCase], suite_name: str, n_tests: int) -> FidelityReport:
    report = FidelityReport(
        tool="deepeval", suite=suite_name,
        summary=f"{len(cases)} qval cases -> {n_tests} deepeval tests.",
    )
    paired_ids = [c.id for c in cases if c.paired_prompt]
    all_detectors = sorted({d for c in cases for d in c.detectors})

    report.add("prompt", CLEAN, "-> LLMTestCase.input")
    report.add("expected_behavior", CLEAN, "-> GEval criteria string")
    report.add("name / description", CLEAN, "-> test docstring")
    report.add(
        "paired_bias_prompts",
        CLEAN if paired_ids else DEGRADED,
        f"{len(paired_ids)} case(s) expanded to a second `_paired` test"
        if paired_ids else "no paired cases in this suite",
        case_ids=paired_ids,
    )
    report.add("detectors", DROPPED,
               f"no deepeval equivalent; preserved in docstring only: "
               f"{', '.join(all_detectors) or 'none'}")
    report.add("risk_level", DEGRADED, "-> test docstring only (not enforced)")
    report.add("manual_review_required", DEGRADED, "-> test docstring only")
    report.add("scoring_type", DEGRADED, "-> test docstring only")
    report.add("tags", DROPPED, "no deepeval equivalent")
    return report


# Self-register on import so the registry / CLI discover this tool.
register(DeepEvalExporter())
